### ISSUE TITLE
You're late

### ISSUE THREAD

**Issue by Munto** [jwise/aoc#1]
I miss your stream in lua :heart:

**Comment by jwise** [comment]
Aw ❤️ I guess I can't argue with that.

I've been solving the first few days but haven't gotten my stuff together to stream.  I don't think I'm going to manage to stream tonight (though I will try to speed-solve from a bar, and if connectivity permits, I *guess* I could try to stream...), but I anticipate that I'll get back to it tomorrow.

**Comment by jwise** [comment]
OK IT IS LIVE GO GO GO I AM DRINKING.

**Comment by jwise** [comment]
https://www.youtube.com/watch?v=okR_Spf4zFI Here was last night's.  I'm not sure if I'll get to stream tonight.  We'll see.  I'll close this once I actually start reliably streaming and when I push my code :)

**Comment by Munto** [comment]
Hey, that's really nice!
Thank you 🙂

**Comment by jwise** [comment]
Ok, I pushed.  And I think I've figured out how to reliably stream again.  Thanks for the reminder!
